services:
  - type: web
    name: booking-alert-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    pythonVersion: 3.13.0
